# -*- coding: utf-8 -*-
"""Generate a fully-synthetic 23andMe-format file covering every rsID the engines use,
so `run.py` produces a complete EXAMPLE dashboard with NO real person's data.

Deterministic (fixed seed). Genotypes are fabricated; the mtDNA diagnostic positions are
set to spell out one haplogroup so the ancestry panel populates. This is a demo fixture."""
import json, os, random, re
REF = os.path.join(os.path.dirname(__file__), "..", "reference")
random.seed(42)

def load(f): return json.load(open(os.path.join(REF, f), encoding="utf-8"))

rows = {}  # rsid -> (chrom, pos, genotype)
pos_counter = [1000]
def put(rsid, chrom, geno):
    pos_counter[0] += 137
    rows[rsid] = (chrom, pos_counter[0], geno)

# 1) catalog SNPs — pick a real genotype key so every card renders with an interpretation
for e in load("catalog.json"):
    keys = [k for k in e["gt"].keys() if k not in ("--",)]
    put(e["rsid"], "1", random.choice(keys))

# 2) PRS weights — valid diploid over {risk allele, a complement-ish other}
bases = "ACGT"
for trait, ents in load("prs_weights.json").items():
    for r in ents:
        ra = r["risk_allele"]; other = random.choice([b for b in bases if b != ra])
        put(r["rsid"], "1", "".join(sorted(random.choice([ra+ra, ra+other, other+other]))))

# 3) pgx + carrier catalogs
for e in load("pgx_catalog.json"):
    if "gt" in e:                                   # single-SNP entry
        put(e["rsid"], "1", random.choice(list(e["gt"].keys())))
    for a in e.get("alleles", []):                  # gene-level entry (Task 5)
        put(a["probes"][0], "1", random.choice([a["ref"]*2, a["ref"]*2, a["ref"]+a["alt"]]))
for e in load("carrier_catalog.json"):
    if e.get("untestable"):
        continue
    gts = [e["ref"]*2]*6 + ["".join(sorted(e["ref"]+e["alt"]))]   # mostly normal, sometimes a carrier
    gt = random.choice(gts)
    put(e["probes"][0], "1", gt)
    if e["rsid"] != e["probes"][0]:                  # also under the rsID so the VCF round trip covers it
        put(e["rsid"], "1", gt)

# 4) Neanderthal panel — random of its two alleles
for rs, d in load("neanderthal_panel.json").items():
    put(rs, "1", "".join(sorted(random.choice([d["AA"]*2, d["AA"]+d["OOA"], d["OOA"]*2]))))

# 5) ancestry AIMs — random diploid
for rs in ["rs1426654","rs16891982","rs2814778","rs3827760","rs1229984","rs17822931","rs671",
           "rs12913832","rs1042602","rs260690","rs174570","rs7554936","rs2946788","rs7657799",
           "rs2504853","rs2416791","rs1800407","rs1129038","rs459920","rs3785181","rs4471745",
           "rs11652805","rs12203592","rs4988235"]:
    rows.setdefault(rs, ("1", pos_counter[0], "".join(sorted(random.choice(["AA","AG","GG","CC","CT","TT"])))))

# 6) mtDNA — spell out haplogroup J so the caller returns something (chrom MT, real positions)
mt = {263:"G",1438:"G",4216:"C",10398:"G",13708:"A",11719:"A",7028:"T",8860:"G",14766:"T",15326:"G",
      11467:"A",12308:"A",12372:"G",1719:"G",3010:"G",4580:"G"}
for p, b in mt.items():
    rows[f"i{p}"] = ("MT", p, b)

# 7) a handful of Y backbone SNPs (chrom Y) so the Y panel isn't empty
for rs, allele in {"rs9786714":"A","rs2032597":"A","rs9341278":"G","rs17307677":"T","rs9786153":"T"}.items():
    rows[rs] = ("Y", pos_counter[0], allele); pos_counter[0]+=1

# 8) some filler autosomal homozygous SNPs so ROH / chromosome coverage looks populated
for i in range(4000):
    rows[f"rsMOCK{i}"] = (str(1+i%22), 5000+i*900, random.choice(["AA","GG","CC","TT","AG","CT"]))

out = os.path.join(os.path.dirname(__file__), "..", "examples", "mock_person.txt")
os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, "w", encoding="utf-8") as fh:
    fh.write("# This is a SYNTHETIC example file — fabricated genotypes, NOT a real person.\n")
    fh.write("# Generated by scripts/make_mock.py for the example dashboard.\n")
    fh.write("# rsid\tchromosome\tposition\tgenotype\n")
    for rsid,(ch,p,g) in rows.items():
        fh.write(f"{rsid}\t{ch}\t{p}\t{g}\n")
print("wrote", out, "with", len(rows), "synthetic SNPs")
